title: Cristian Del Gobbo
logo: Asset/Gobbo_Headshot2-modified (1).png
description: Hello, and welcome to my Data Science portfolio. Here, you will find a collection of my projects, research, and contributions in the field of data science.
show_downloads: false
#theme: jekyll-theme-minimal
#theme: jekyll-theme-Cayman
#theme: jekyll-theme-Hacker
theme: jekyll-theme-Tactile
