title: Cristian Del Gobbo
logo: Asset/Gobbo_Headshot2-modified.png
description: Hello, and welcome to my Data Science portfolio. I am a dedicated and passionate student pursuing a double major in Data Science and Mathematics with a minor in Business Administration at Lyon College. Here, you will find a collection of my projects, research, and contributions in the field of data science.
show_downloads: true
theme: jekyll-theme-minimal
